export const storage = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    rating: 4.69,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/1/1.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    rating: 4.44,
    brand: "Apple",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/2/1.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    rating: 4.09,
    brand: "Samsung",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/3/1.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    rating: 4.3,
    brand: "OPPO",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/4/1.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    rating: 4.09,
    brand: "Huawei",
    category: "smartphones",
    image: "https://i.dummyjson.com/data/products/5/1.jpg",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    rating: 4.57,
    brand: "Apple",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/6/1.png",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    price: 1499,
    rating: 4.25,
    brand: "Samsung",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/7/1.jpg",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    price: 1499,
    rating: 4.43,
    brand: "Microsoft Surface",
    category: "laptops",
    image: "https://i.dummyjson.com/data/products/8/1.jpg",
  },
];
